M48
; DRILL file {KiCad 9.0.6} date 2025-11-10T09:59:30-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-10T09:59:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X119.0Y-68.0
X119.0Y-115.0
X176.6Y-68.0
X176.6Y-115.0
M30
